-- Schema base
CREATE TABLE IF NOT EXISTS usuarios (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) NOT NULL,
  email VARCHAR(150) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL DEFAULT 'admin',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clientes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(150) NULL,
  telefone VARCHAR(50) NULL,
  suite VARCHAR(50) NULL,
  endereco VARCHAR(255) NULL,
  observacoes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS vendas (
  id INT AUTO_INCREMENT PRIMARY KEY,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  numero_pedido VARCHAR(100) NULL,
  cliente_id INT NULL,
  usuario_id INT NULL,
  suite VARCHAR(50) NULL,
  peso_kg DECIMAL(10,2) NOT NULL DEFAULT 0,
  valor_produto_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  taxa_servico_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  servico_compra_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  produto_compra_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  frete_brl DECIMAL(12,2) NOT NULL DEFAULT 0,
  frete_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  bruto_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  bruto_brl DECIMAL(12,2) NOT NULL DEFAULT 0,
  liquido_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  liquido_brl DECIMAL(12,2) NOT NULL DEFAULT 0,
  comissao_usd DECIMAL(12,2) NOT NULL DEFAULT 0,
  comissao_brl DECIMAL(12,2) NOT NULL DEFAULT 0,
  FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE SET NULL,
  FOREIGN KEY (usuario_id) REFERENCES usuarios(id) ON DELETE SET NULL,
  INDEX (cliente_id), INDEX (usuario_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  `key` VARCHAR(100) PRIMARY KEY,
  `value` VARCHAR(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS logs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  usuario_id INT NULL,
  entidade VARCHAR(50) NOT NULL,
  acao VARCHAR(50) NOT NULL,
  ref_id INT NULL,
  detalhes TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX (usuario_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Valor padrão para taxa do dólar
INSERT INTO settings(`key`, `value`) VALUES ('usd_rate', '5.83')
  ON DUPLICATE KEY UPDATE `value`=VALUES(`value`);
